#!/usr/bin/env python
"""
monitor_creation - by Frederick Ross <madhadron@gmail.com>

This is an example daemon that uses the pydaemonize.inotify stock
daemon. You will have to have pyinotify (available from
http://github.com/seb-m/pyinotify) installed to use it.

It monitors ``/tmp`` for file creations, and prints a message to
syslog for each such creation.
"""
# Remove this line to use the system wide version of pydaemonize:
import sys; sys.path.insert(1, '../')

import pydaemonize
import pyinotify
import syslog

class FileCreation(pydaemonize.Daemon):
    def action(self):
        """Monitor file creation in /tmp"""
        class Handler(pyinotify.ProcessEvent):
            def process_IN_UNMOUNT(self, event):
                syslog.syslog(syslog.LOG_NOTICE, "Backing filesystem of %s was unmounted. Exiting." % event.path)
                exit(0)
            def process_default(self, event):
                syslog.syslog(syslog.LOG_NOTICE, 'File %s created in %s' % \
                                  (event.name, event.path))

        wm = pyinotify.WatchManager()
        notifier = pyinotify.Notifier(wm, Handler())
        wm.add_watch('/tmp', pyinotify.IN_CREATE, rec=True)
        notifier.loop()


if __name__=='__main__':
    FileCreation(detach=False, pidfilepath=None)



