#!/usr/bin/env python
"""
nop_daemon.py - by Frederick Ross <madhadron@gmail.com>

This is the simplest possible daemon you can produce with
pydaemonize. It does nothing, forever.
"""
# Remove this line to use the system wide version of pydaemonize: 
import sys; sys.path.insert(1, '../') 

import pydaemonize

class NopDaemon(pydaemonize.Daemon):
    def action(self):
        """Do nothing forever."""
        while True:
            pass

if __name__=='__main__':
    NopDaemon(detach=False, pidfilepath=None)
